defaults: &defaults
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  timeout: 5000
  pool: 5

development:
  database: fs_course_ananiev_dev
  <<: *defaults

test:
  database: fs_course_ananiev_test
  <<: *defaults

production:
  <<: *defaults
